import { pool } from "../Connetion/db.js";

export async function GetCars(NombreOperativo) {
  try {
    const tipoCars = [
      "HSX795",
      "GJU140",
      "GCU826",
      "CWZ891",
      "MGY346",
      "JZM050",
      "CUX039",
      "HPW184",
      "LTO423",
    ];

    const conductores = [
      { placa: "SPT58G", operador: "JHORDAN ARIZA" },
      { placa: "SOP09F", operador: "JHAWI BOHORQUEZ" },
      { placa: "XHU36G", operador: "HERMES ORTIZ" },
      { placa: "YOB35F", operador: "VACCA EDIL" },
      { placa: "MWG85G", operador: "JORGE PIZARRO" },
      { placa: "EMK84F", operador: "GOMEZ ALBEIRO" },
      { placa: "HKB97G", operador: "MANOSALVA JAIDER" },
      { placa: "HGO10F", operador: "GONGORA DAGOBERTO" },
      { placa: "EYV68G", operador: "HAROLD GARCIA" },
      { placa: "TVM87G", operador: "FABIO GUTIERREZ" },
      { placa: "SOO60F", operador: "JOSE NOVOA" },
      { placa: "LIA78F", operador: "CARLOS SANCHEZ" },
      { placa: "MRZ64G", operador: "ALBERTO AGUAS" },
      { placa: "YWT88F", operador: "EDWARD GALINDO" },
      { placa: "YDS14E", operador: "DIEGO PEREZ" },
      { placa: "KLR57H", operador: "EDUAR CORAL" },
      { placa: "QBN44F", operador: "EDGAR MENDOZA" },
      { placa: "GIR81H", operador: "JHOSER CORAL" },
      { placa: "XQM95G", operador: "YAIR YAÑEZ" },
      { placa: "SAK91H", operador: "YESID ALVAREZ" },
      { placa: "KQG62H", operador: "FREDDY ALADINO" },
      { placa: "MGD18G", operador: "DARWIN JAIMES" },
      { placa: "YEL18E", operador: "MARIA RODRIGUEZ" },
      { placa: "NLM26F", operador: "RICARDO JIMENEZ" },
      { placa: "YXU84E", operador: "CARRILLO CRISTIAN" },
      { placa: "KKV67H", operador: "EDGAR JAIMES" },
      { placa: "GQE77G", operador: "DIEGO FLOREZ" },
      { placa: "QBU18F", operador: "PEREZ FREIMAN" },
      { placa: "VYA21H", operador: "JESUS ROLON" },
      { placa: "PWX20F", operador: "ANDERSON FLORES" },
      { placa: "SQD42G", operador: "FABIAN BUELVAS" },
      { placa: "NMF74F", operador: "MIRYAM SIERRA" },
      { placa: "QBO59F", operador: "OSCAR PATIÑO" },
      { placa: "CDP11H", operador: "YEISON BOTELLO" },
      { placa: "ZJS69E", operador: "ISMAEL TORRES" },
      { placa: "INY58G", operador: "JAIMES EDSON" },
      { placa: "AIQ28G", operador: "PEDRO DIAZ" },
      { placa: "XOT17F", operador: "EDWIN QUINTERO" },
      { placa: "GRS33G", operador: "SANCHEZ ARIDES" },
      { placa: "BLX15H", operador: "JULIO QUESADA" },
      { placa: "DJX79G", operador: "LUIS TORRADO" },
      { placa: "GRK27G", operador: "JESUS LOPEZ" },
      { placa: "ZJW58E", operador: "FREIMAN AREVALO" },
      { placa: "DJU33G", operador: "DIEGO RINCON" },
      { placa: "KIV05G", operador: "CRISTHIAN PEÑARANDA" },
      { placa: "KJC91G", operador: "JHON ROPERO" },
      { placa: "MTV31G", operador: "PEREZ ALEXANDER" },
      { placa: "XOL16F", operador: "JORGE DURAN" },
      { placa: "HKC14G", operador: "LAZARO DIEGO" },
      { placa: "DQP50F", operador: "BLANCO JONATHAN" },
      { placa: "OUR11F", operador: "BLANCO WISTON" },
      { placa: "RYE65F", operador: "LOPEZ ANDREY" },
      { placa: "RYG39F", operador: "RIOS SOLANGEL" },
      { placa: "IPJ43G", operador: "OSCAR CALVO" },
      { placa: "HCQ03H", operador: "MACHADO BREIDER" },
      { placa: "WYM96G", operador: "SANGUINO WILLIAM" },
      { placa: "DJT07G", operador: "PEREZ BRAYAN" },
      { placa: "TVM21G", operador: "YORMAN PEREZ" },
      { placa: "INT15G", operador: "RICARDO ANTELIZ" },
      { placa: "JXK08G", operador: "HEYSON ARIAS" },
      { placa: "YEP42G", operador: "ALLEX BOHORQUEZ" },
      { placa: "YXC95F", operador: "JUAN CALDERON" },
      { placa: "KMF52H", operador: "SAID CONTRERAS" },
      { placa: "NOT67H", operador: "JEAN CONTRERAS" },
      { placa: "DAR70G", operador: "LUIS CONTRERAS" },
      { placa: "IMX90G", operador: "BRALLAM CONTRERAS" },
      { placa: "KQX34H", operador: "HOBER DAVILA" },
      { placa: "XQK45G", operador: "PEÑARANDA ELKLIN" },
      { placa: "YDJ55G", operador: "JEAN SANTIAGO" },
      { placa: "ZRA89F", operador: "LUIS ORTIZ" },
      { placa: "FCK32F", operador: "PEDRAZA ISRAEL" },
      { placa: "QCG55F", operador: "BLANCO CARLOS" },
      { placa: "PVX53G", operador: "DIONEL CLAVIJO" },
      { placa: "GRV36G", operador: "JESUS HERNANDEZ" },
      { placa: "CDZ96H", operador: "MIGUEL FLOREZ" },
      { placa: "QBI93F", operador: "ROJAS HERMES" },
      { placa: "QBG89F", operador: "GIOVANNY TORRES" },
      { placa: "XPZ20G", operador: "LUIS DIAZ" },
      { placa: "CCR09H", operador: "ORELLANOS JABES" },
      { placa: "NME04F", operador: "CONTRERAS EDGARDO" },
      { placa: "YYI30F", operador: "JEAN BAYONA" },
      { placa: "DBL27G", operador: "CRISTIAN LOPEZ" },
      { placa: "ZRG71F", operador: "EUDIN TRUJILLO" },
      { placa: "MTN04G", operador: "CHACON YENSYN" },
      { placa: "YFD99E", operador: "SANCHEZ EDUARD" },
      { placa: "PWA73F", operador: "JAIRO CAMARGO" },
      { placa: "TZD83G", operador: "JEAN DURAN" },
      { placa: "MRS61G", operador: "SANCHEZ WILSON" },
      { placa: "MSD43G", operador: "JUAN ANGARITA" },
      { placa: "SGS12G", operador: "MARTINEZ ANDERSON" },
      { placa: "YXM74F", operador: "ALVARO GONZALEZ" },
      { placa: "PMP84H", operador: "JESUS PEÑA" },
      { placa: "DJY95F", operador: "CRISTIAN NORIEGA" },
      { placa: "IOK99G", operador: "LEDYD GARCIA" },
      { placa: "XPZ70G", operador: "NELSON GARCIA" },
      { placa: "YCV54G", operador: "RAMON TORRES" },
      { placa: "XPS30G", operador: "LUVER CASTELLANOS" },
      { placa: "HCY84H", operador: "VICTOR SALCEDO" },
      { placa: "ZKO28E", operador: "JOSE ORTIZ" },
      { placa: "QBP67F", operador: "JONATHAN ESTUPIÑAN" },
      { placa: "QNZ91G", operador: "JOSE CASTRO" },
      { placa: "YXU51F", operador: "FRANCISCO GALAN" },
      { placa: "EFP20H", operador: "EDWIN FLOREZ" },
      { placa: "PXQ20G", operador: "URIBE ALEXIS" },
      { placa: "KKT72H", operador: "ANDRES ALEXANDER" },
      { placa: "WRD65F", operador: "NESTOR MORENO" },
      { placa: "MGR10G", operador: "LUIS TRIANA" },
      { placa: "NHF59D", operador: "DIEGO MEDINA" },
      { placa: "WYO54G", operador: "SANCHEZ DEIMER" },
      { placa: "KKY76H", operador: "KEWIN CAMARGO" },
      { placa: "JGB09F", operador: "DURAN ELISAIR" },
      { placa: "NMW69H", operador: "TULIO RODRIGUEZ" },
      { placa: "NOA79H", operador: "EDGAR ASCENCIO" },
      { placa: "NMD57F", operador: "ELKIN PEÑA" },
      { placa: "NOX08H", operador: "JHON PEREZ" },
      { placa: "YXT55F", operador: "BORIS PEÑA" },
      { placa: "LTK74C", operador: "ELVER PEÑALOZA" },
      { placa: "YDW50E", operador: "MARCOS SUAREZ" },
      { placa: "MSS71G", operador: "EDINSON CARRASCAL" },
      { placa: "EGM64H", operador: "ALBER VERGARA" },
      { placa: "IMX65G", operador: "CARLOS VERA" },
      { placa: "ZSC31F", operador: "EDWIN SANABRIA" },
      { placa: "KKY94H", operador: "PAULA CONTRERAS" },
      { placa: "IAH14G", operador: "RAFHAEL PABON" },
      { placa: "WZJ02H", operador: "PEREZ ALEXANDER" },
      { placa: "KKZ37H", operador: "JESUS URQUIJO" },
      { placa: "TVU15G", operador: "CARREÑO YEISON" },
      { placa: "ANT36E", operador: "CARLOS MARQUEZ" },
      { placa: "YDK93G", operador: "OSCAR RODRIGUEZ" },
      { placa: "NLX59F", operador: "JOSE FORERO" },
      { placa: "TZC05G", operador: "CORREA ANDERSON" },
      { placa: "SBV76H", operador: "JOHAN GALVIS" },
      { placa: "CCX27H", operador: "IVAN PEÑARANDA" },
      { placa: "ARI40I", operador: "JUAN VILLEGAS" },
      { placa: "ZPU62H", operador: "RUEDA JENER" }
    ];
    const placa = conductores.find(o => o.operador === NombreOperativo)?.placa; // Reemplaza "SPT58G" con la placa que deseas buscar
    const [rows] = await pool.execute("SELECT * FROM cars WHERE alias = ?", [placa]);
    // recorrer el array de resultados y mostrar algunas propiedaddes con map

    const cars = rows.map((car) => ({
      alias: car.alias,
      longitude: car.longitude,
      latitude: car.latitude,
      speed: car.speed,
      active: car.active,
      conductor: conductores.find(o => o.placa === car.alias)?.operador,
      marker_color: car.active === "ONLINE" ? car.marker_color : "#FF2C2C",
      type: tipoCars.includes(car.alias) ? "carro" : "moto", // Asigna el tipo basado en el alias
    }));

    // console.log(rows[0]);
    return cars.length > 0 ? cars : null;
  } catch (error) {
    console.error(`Error al consultar correria:`, error);
    return null;
  }
}
